### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by Pillar1989** [Seeed-Studio/ardupy-aip#1]
* [x]  add  build, install, flash command
* [x]  publish to PyPi
* [x]  add ci-travis
* [x]  documentation of all commands
* [x]  add uninstall command
* [x]  add REPL command
* [x]  add files command
* [x]  handle different boards, set global variables? 
* [x]  the Ardupy module may not be on GitHub. What should I do? 
* [x]  shadow repositories cannot be downloaded using pygit2, and specific versions need to be considered.
